name: Build C Project

on:
  push:
    paths-ignore:
      - '1lab/**'
      - '2lab/**'
      - '3lab/**'
      - '4lab/**'
      - '5lab/**'
  pull_request:
    paths-ignore:
      - '1lab/**'
      - '2lab/**'
      - '3lab/**'
      - '4lab/**'
      - '5lab/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install compiler and make
      run: sudo apt-get install -y build-essential
      
    - name: Build with Make
      run: make
      
    - name: Run program
      run: ./main
