name: Build C Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install compiler and make
      run: sudo apt-get install -y build-essential
      
    - name: Build with Make
      run: make
      
    - name: Run program
      run: ./main
