name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Valgrind
      run: sudo apt-get install -y valgrind

    - name: Build and Test
      run: |
        cd 6lab
        make
        
    - name: Check for Memory Leaks
      run: |
        cd 6lab
        valgrind --leak-check=full --error-exitcode=1 ./main
  
    - name: Build and Test
      run: |
        cd 7lab
        make
        
     - name: Build and Test
      run: |
        cd 8lab
        make

    - name: Build and Test
      run: |
        cd 9lab/1ex
        make
    
    -name: Build and Test
      run: |
        cd 9lab/2ex
        make
        
    
        
