name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CC: gcc
  CXX: g++

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: ['6lab', '7lab', '8lab', '9lab/1ex', '9lab/2ex']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind build-essential

    - name: Build ${{ matrix.lab }}
      run: |
        cd ${{ matrix.lab }}
        make
        
    - name: Run tests for ${{ matrix.lab }}
      run: |
        cd ${{ matrix.lab }}
        case ${{ matrix.lab }} in
          "6lab")
            valgrind --leak-check=full --error-exitcode=1 ./main
            ;;
          "7lab")
            echo -e "1\n5\n10\n5\n5" | ./main || true
            ;;
          "8lab")
            echo -e "1\n5\n10\n5\n5" | ./calcul || true
            ;;
          "9lab/2ex")
            echo -e "q\n" | ./test || true
            ;;
        esac

    - name: Clean build artifacts
      if: always()
      run: |
        cd ${{ matrix.lab }}
        make clean || true

    - name: Check code formatting
      run: |
       find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
    
  